# Generated by Django 3.1.6 on 2021-02-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('maintain_req', models.IntegerField()),
            ],
            options={
                'db_table': 'House',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Housemate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Housemate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_num', models.IntegerField()),
                ('level_name', models.CharField(max_length=16)),
                ('wear_level', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'House_Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Individual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwd_hash', models.CharField(max_length=85)),
            ],
            options={
                'db_table': 'Login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_elo', models.IntegerField()),
                ('assign_date', models.DateField(blank=True, null=True)),
                ('deadline_date', models.DateTimeField(blank=True, null=True)),
                ('has_recur', models.IntegerField()),
            ],
            options={
                'db_table': 'Task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskRecurrence',
            fields=[
                ('recur_id', models.AutoField(primary_key=True, serialize=False)),
                ('freq_time', models.TimeField()),
                ('freq_days', models.IntegerField()),
                ('freq_weeks', models.IntegerField()),
                ('freq_year', models.IntegerField()),
            ],
            options={
                'db_table': 'Task_Recurrence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('task_state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'db_table': 'Task_State',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('relation_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'User_Relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('cr_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
