# Generated by Django 3.1.6 on 2021-02-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Housemate',
        ),
        migrations.DeleteModel(
            name='HouseStatus',
        ),
        migrations.DeleteModel(
            name='Individual',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskRecurrence',
        ),
        migrations.DeleteModel(
            name='TaskState',
        ),
        migrations.DeleteModel(
            name='UserRelation',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
