# Generated by Django 3.1.6 on 2021-02-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_house_housemate_housestatus_individual_login_task_taskrecurrence_taskstate_userrelation_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
